apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: dotenvx-action
  description: null
  annotations:
    github.com/project-slug: pats/dotenvx-action
  tags:
    - frontend
    - codesnoop
spec:
  owner: actions-oss-maintainers
